-- ============================================================
-- LSRW Skills Platform — Full Database Schema v2
-- Run this in Supabase SQL Editor (Dashboard → SQL Editor)
-- ============================================================

-- ── 1. PROFILES ────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS profiles (
    id                UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    full_name         TEXT,
    college_name      TEXT,
    gender            TEXT DEFAULT 'male',
    avatar_url        TEXT,
    current_streak    INT  DEFAULT 0,
    longest_streak    INT  DEFAULT 0,
    last_active_date  DATE,
    total_attempts    INT  DEFAULT 0,
    updated_at        TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can insert own profile"  ON profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can view own profile"    ON profiles FOR SELECT  USING  (auth.uid() = id);
CREATE POLICY "Users can update own profile"  ON profiles FOR UPDATE  USING  (auth.uid() = id);

-- ── 2. SCORES ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS scores (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        UUID  REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    module_type    TEXT  NOT NULL,
    score_achieved INTEGER NOT NULL,
    total_score    INTEGER NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE scores ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own scores"   ON scores FOR SELECT  USING  (auth.uid() = user_id);
CREATE POLICY "Users can insert own scores" ON scores FOR INSERT  WITH CHECK (auth.uid() = user_id);

-- ── 3. BADGES ──────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS badges (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
    badge_id   TEXT NOT NULL,
    earned_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE (user_id, badge_id)
);

ALTER TABLE badges ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own badges"   ON badges FOR SELECT  USING  (auth.uid() = user_id);
CREATE POLICY "Users can insert own badges" ON badges FOR INSERT  WITH CHECK (auth.uid() = user_id);

-- ── 4. QUESTIONS (optional) ────────────────────────────────
CREATE TABLE IF NOT EXISTS questions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module_type TEXT  NOT NULL,
    content     JSONB NOT NULL,
    difficulty  TEXT  DEFAULT 'beginner',
    created_at  TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ── 5. AUTO-CREATE PROFILE ON SIGNUP ───────────────────────
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO public.profiles (id, full_name, gender)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'full_name', 'Student'),
        COALESCE(NEW.raw_user_meta_data->>'gender', 'male')
    )
    ON CONFLICT (id) DO NOTHING;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ── 6. STREAK LEADERBOARD RPC ──────────────────────────────
-- Returns top-10 current streaks (first-name only, safe for public display).
-- Call via: supabase.rpc('get_streak_leaderboard')
CREATE OR REPLACE FUNCTION public.get_streak_leaderboard()
RETURNS TABLE(
    display_name   TEXT,
    current_streak INT,
    longest_streak INT,
    total_attempts INT
)
LANGUAGE SQL
SECURITY DEFINER
SET search_path = public
AS $$
    SELECT
        SPLIT_PART(COALESCE(full_name, 'Student'), ' ', 1) AS display_name,
        COALESCE(p.current_streak, 0)  AS current_streak,
        COALESCE(p.longest_streak, 0)  AS longest_streak,
        COALESCE(p.total_attempts, 0)  AS total_attempts
    FROM profiles p
    WHERE COALESCE(p.current_streak, 0) > 0
    ORDER BY p.current_streak DESC, p.longest_streak DESC
    LIMIT 10;
$$;

-- ── 7. SUPABASE STORAGE — avatars bucket ───────────────────
-- Run in SQL Editor to create the avatars bucket and policy:
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Anyone can view avatars"
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

CREATE POLICY "Users can upload own avatar"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

CREATE POLICY "Users can update own avatar"
ON storage.objects FOR UPDATE
USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

-- ── NOTE: Daily emails ──────────────────────────────────────
-- Deploy supabase/functions/daily-reminder then schedule with:
-- Dashboard → Edge Functions → daily-reminder → Cron → 0 18 * * *
-- Required secrets: RESEND_API_KEY, FROM_EMAIL, APP_URL
